site_name: MySQL Time Machine

pages:
    - Overivew: index.md
    - User Guide:
        - Binlog Flusher: 'binlog_flusher.md'
        - Active Schema: 'active_schema.md'
        - Running the Replicator: 'replicator.md'
        - Hadoop/Hive Imports: 'snapshotter.md'
        - Setting up the Validator: 'validator.md'
        - Failover Options: 'failover_options.md'
    - About: about.md
theme: readthedocs
markdown_extensions:
    - smarty
    - toc:
        permalink: True
        separator: "_"
    - sane_lists
